apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-configmap
  namespace: prod-petclinic
data:
  poststart.sql: |
    #!/bin/bash
    CREATE TABLE IF NOT EXISTS vets (
      id INT(4) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
      first_name VARCHAR(30),
      last_name VARCHAR(30),
      INDEX(last_name)
    ) engine=InnoDB;
