apiVersion: v1 
kind: Service 
metadata:
  name: petclinicapp
  namespace: prod-petclinic
spec:
  selector:
    app: petclinicapp
  ports:
  - name: petclinicapp
    nodePort: 30082
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: petclinicapp1
    nodePort: 30083
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: petclinicapp
  type: LoadBalancer
