kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: petclinic-claim
  #namespace: default
  namespace: prod-petclinic
spec:
  storageClassName: managed-nfs-storage 
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi
