apiVersion: v1
kind: ConfigMap
metadata:
  name: petclinic-configmap
  namespace: prod-petclinic
data:
  application.properties: |
    database=mysql
    spring.datasource.url=jdbc:mysql://mysql/petclinic
    spring.datasource.username=petclinic
    spring.datasource.password=petclinic
    spring.sql.init.mode=always
    spring.thymeleaf.mode=HTML
    spring.jpa.hibernate.ddl-auto=none
    spring.jpa.open-in-view=true
    spring.messages.basename=messages/messages
    management.endpoints.web.exposure.include=*
    logging.level.org.springframework=DEBUG
    logging.level.org.springframework.web=DEBUG
    logging.level.org.springframework.context.annotation=TRACE
    spring.web.resources.cache.cachecontrol.max-age=12h
    spring.profiles.active=mysql
    #spring.jpa.show-sql=true
    #spring.jpa.hibernate.ddl-auto=create
    #spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
