apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinicapp
  namespace: prod-petclinic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: petclinicapp
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: petclinicapp
    spec:
      containers:
      - name: petclinicapp
        image: anoophegde1995/springboot-petclinic_deploy:f15909a9b3460d3ffee74794835938d474ad28cb
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        volumeMounts:
          - name: log-dir
            mountPath: /apps/logs/Springboot-PetClinic
          - name: appconfig
            mountPath: "/apps/configuration/Springboot-PetClinic"
      volumes:
        - name: log-dir
          hostPath:
            path: /apps/logs/Springboot-PetClinic
            type: DirectoryOrCreate
        - name: appconfig
          configMap:
            name: petclinic-configmap
